### ISSUE TITLE
add default login endpoint

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#120]
`/login` should provide high level information like:
```
{
"default_provider": {
    "name": "NIH Login",
    "url": "BASE_URL/login/shib"},
"providers": [
    {"name": "NIH Login",
    "url": "BASE_URL/login/shib"}
]
}
```
So that a Commons's portal can know what login options to support
blocks https://github.com/uc-cdis/data-portal/issues/228

**Comment by rudyardrichter** [comment]
Time spent: 3.5 hours
