### ISSUE TITLE
test presigned url generation

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#136]
create jenkins integration tests to make sure:
- you can generate presigned url and download for public data without token
- can't generate presigned url for protected data without token or with expired/unauthorized token
- can generate presigned url and download for protected data with token
- url expires properly (try with expires=1)

**Comment by trevars** [comment]
Will call Indexd

**Comment by thanh-nguyen-dang** [comment]
https://github.com/uc-cdis/auto-qa/pull/1
