### ISSUE TITLE
allow fence syncing from both dbgap and user.yaml

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#145]
for kids first production system,
we need to sync from dbgap for general user's lists, and sync from kids first's for submitter list.
We should allow the dbgap syncing job to combine those lists and  use them as the source of truth for allowed user.
- allow [sync from dir](https://github.com/uc-cdis/fence/blob/master/fence/sync/sync_dbgap.py#L327) to happen together with syncing from dbgap
- adjust [csv syncing](https://github.com/uc-cdis/fence/blob/master/fence/sync/sync_dbgap.py#L142) to populate the acl dict with actions that can be merged

**Comment by giangbui** [comment]
Spent about 8 hours

**Comment by giangbui** [comment]
Blocked by sftp server setup
