### ISSUE TITLE
DCF >SBG > QA issue> getting invalid_client response (401 status)

### ISSUE THREAD

**Issue by gneglur** [uc-cdis/fence#156]
1) we are trying to trigger below request but we are getting invalid_client response (401 status)

2)POST /user/oauth2/token HTTP/1.1
Host: qa.dcf.planx-pla.net
Content-Type: application/x-www-form-urlencoded
Authorization: Basic base64(clientId:clientSecret)
Cache-Control: no-cache

grant_type=authorization_code&code=LCoRD9YgblA5ok9RMw9ORVHRZYFGvIJ4cT19BxgAgpryOMw8zB&redirect_uri=https%3A%2F%2FFaccounts-ncrdc-vayu.sbgenomics.com%2FFproviders%2FFopenid%2Fgen3%2Fredirect-callback

3) P.S. Just a small note, client secret that you send to us is 55 characters long, but for kids first effort is 56 characters long - I know that length is not important, but just want to check if it is maybe copy paste error

**Comment by gneglur** [comment]
Fixed by Thanh. SBG Igor to verify.

**Comment by thanh-nguyen-dang** [comment]
spent 2 hours
