### ISSUE TITLE
PXD-275 ⁃ Add Guide for local_settings.py

### ISSUE THREAD

**Issue by lemccarthy** [uc-cdis/fence#168]
Hi,

I'm trying to set up Fence to use with my project, and I'm having trouble understanding some of the process. The installation instructions simply tell you to fill out `local_settings.py`. Some of them are obvious e.g. database credentials, google oauth, but others are not, for example:

```
STORAGE_CREDENTIALS = {
    "cleversafe-server-a": {
        'backend': 'cleversafe',
        'aws_access_key_id': '',
        'aws_secret_access_key': '',
        'host': 'somemanager.osdc.io',
        'public_host': 'someobjstore.datacommons.io',
        'port': 443,
        'is_secure': True,
        'username': 'someone',
        'password': 'somepass',
        "calling_format": OrdinaryCallingFormat(),
        "is_mocked": True
    }
}
```

I'm not sure what a "cleversafe-server" is, or how I would go about setting one up if it is required. I would appreciate any help you can render in settings this up.

**Comment by philloooo** [comment]
thanks for the feedback, we will add documentation for that, can you tell us what are you trying to use fence for?

**Comment by lemccarthy** [comment]
I work at the Dana Farber Cancer Institute, at the Knowledge Systems Group, and we were looking into authentication/identity providers for our Cancer Immunologic Data Commons project. We want something that can do role-based access control and integrate with other identity providers (mainly Google). But since we do substantial work with the NIH, Fence's support for their log-on was an attractive feature.

**Comment by rudyardrichter** [comment]
@lemccarthy I started a pull request to add more information about the variables in the settings—would love your input for things that could use further clarification.
