### ISSUE TITLE
PXD-274 ⁃ Fence is not checking origin/Referer for csrf

### ISSUE THREAD

**Issue by jbarno** [uc-cdis/fence#171]
Just read through this [post](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet)
The end of that post has a good run through in java. 

We are missing step 1, verifying the origin url. And should be able to gleam the information from one/multiple of [these](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name)

**Comment by jbarno** [comment]
Here's an example: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)#Prevention_measures_that_do_NOT_work

**Comment by jbarno** [comment]
https://github.com/uc-cdis/fence/pull/209/files#diff-feb6ac6f84a84b339e1cd1e1fc97e3daR193
^ All I need to do to get around CSRF currently is have a header named Authorization, doesn't even have to be valid....
Trivially bypassed.

**Comment by philloooo** [comment]
➤ Kyle Schmitt commented:

We should be able to just inject a header, at the nginx level, if I'm reading this all right.

Where woudl like to test it out?

**Comment by philloooo** [comment]
➤ Justin Barnowski commented:

Updated to the permalink that will short circuit:

https://github.com/uc-cdis/fence/blob/159be1e1c0ab6dab2bb47285fb8b85a06f2d8a6f/fence/__init__.py#L192
