### ISSUE TITLE
DCF-> Broad and ISB -> Google Domain name creation

### ISSUE THREAD

**Issue by gneglur** [uc-cdis/fence#174]
1) Create Google domain names - Trevar
 QA domain name, Production domain name

**Comment by trevars** [comment]
QA created.
Production will need to wait to hear back from NCI.

**Comment by trevars** [comment]
Created dcf-qa under planx-pla.net for DCF QA in Google.

**Comment by trevars** [comment]
nci-crdc.datacommons.io for production
