### ISSUE TITLE
sync additional information from dbgap

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#186]
feature request from SBG:
> Regarding the dbGap data we need `email, dbGap userId, first name, last name, phone, role

These fields are included in dbgap csvs from their ftp site but we aren't parsing them before
- modify fence-create script and dbgap syncing script to allow pass these information (email, first_name, last_name, phone_number, dbgap_role)
- These information will also need to be included in both user endpoint and the jwt id token

**Comment by trevars** [comment]
If I heard this right: Current user yaml file should also be able to upload.

**Comment by giangbui** [comment]
Yeah. We can sync the yaml file with additional information(firstname, lastname, phone_numer, etc.) as Phillis mentioned.
