### ISSUE TITLE
PXD-283 ⁃ Research and Design on how to support Consent Codes from DUO

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#214]
[https://github.com/EBISPOT/DUO](https://github.com/EBISPOT/DUO)
 [http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005772](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005772)
 [https://github.com/DataBiosphere/consent-data-use](https://github.com/DataBiosphere/consent-data-use)

when data is submitted to a Commons, it sometimes carries certain restrictions on how the data should be used(usually on case/subject level for cancer data). This is codified in the Data Use Ontology effort. 
 When user applies for data access, they also sign up about how they want to use the data in the Commons.
 The system should provide an automatic way to match the consent code on the user end and the data end, and only give access to data that match the restrictions.

ARTIFACTS need to be produce: 

* Architecture / design diagram for DUOS phase1 Implementation

**Comment by trevars** [comment]
Research ticket. Will start conversation.

**Comment by trevars** [comment]
"Spec out what new stuff we need to add."
- Rudy & Phillis
