### ISSUE TITLE
PXD-284 ⁃ Remove warning from the token-create

### ISSUE THREAD

**Issue by thanh-nguyen-dang** [uc-cdis/fence#226]
```
Warning: A value for key GOOGLE_API_KEY not found. Defaulting to ""...
Warning: A value for key GOOGLE_PROJECT_ID not found. Defaulting to ""...
Warning: A value for key GOOGLE_ADMIN_EMAIL not found. Defaulting to ""...
Warning: A value for key GOOGLE_IDENTITY_DOMAIN not found. Defaulting to ""...
Warning: A value for key GOOGLE_CLOUD_IDENTITY_ADMIN_EMAIL not found. Defaulting to ""...
```
remove those warning from standard output of `fence-create token-create` command

**Comment by rudyardrichter** [comment]
(I recommend just putting this on stderr)

**Comment by philloooo** [comment]
it goes to stderr directly, docker merge both stdout and stderr

**Comment by rudyardrichter** [comment]
I thought that's only if you run docker with a `TTY` open?

**Comment by philloooo** [comment]
typo, k8s merge both. When you do `kubectl logs` it mixes docker's stdout and stderr

**Comment by thanh-nguyen-dang** [comment]
when I run `kubectl exec`, it also has both in the output. And that is the way we run to create the access_token now. Anyway, where do you check those keys?

**Comment by rudyardrichter** [comment]
If you need to run `kubectl exec` to use `fence-create` and don't care about the warnings, then you can just add `2> /dev/null` in the command to ignore them.
