### ISSUE TITLE
ACL checking

### ISSUE THREAD

**Issue by thanh-nguyen-dang** [uc-cdis/fence#227]
Make those lines of code backward-compatible. Previously, we use `metadata.acls`, the new condition skip checking `metadata.acls` when `acl` exists. It should make the union of those two sets.

https://github.com/uc-cdis/fence/commit/62d7e2cb26d62bbb669fa4e31331fbae38a20bd5

**Comment by philloooo** [comment]
the indexd migrate all existing index.metadata['acl'] to index.acl
So you shouldn't need to check both.

**Comment by thanh-nguyen-dang** [comment]
in this case, we need to have it documented somewhere or change the integration test. Because it is failing now.

**Comment by thanh-nguyen-dang** [comment]
or should we run something in indexd service to migrate the old data?

**Comment by thanh-nguyen-dang** [comment]
and also, if user still use the old code to call the new indexd API. Does it still create the metadata.acls or it will create the field acl in index table? In this case, we should have a message notify that the field is obsolete

**Comment by philloooo** [comment]
the indexd service migrate all old data automatically

**Comment by philloooo** [comment]
it's documented in indexd, and yeah we should update the integration tests
