### ISSUE TITLE
PXD-287 ⁃ Setup staging buckets to log access

### ISSUE THREAD

**Issue by Avantol13** [uc-cdis/fence#231]
Manually set up staging buckets to log access in another google bucket.
https://cloud.google.com/storage/docs/access-logs

Bonus points for testing the bucket-create script in fence-create to ensure that providing an access logging bucket during bucket creation actually sets everything up and logs access.

**Comment by philloooo** [comment]
➤ Alex commented:

[https://cloud.google.com/storage/docs/access-logs](https://cloud.google.com/storage/docs/access-logs)

Setup in staging

**Comment by philloooo** [comment]
➤ Alex commented:

Staging logs: gs://dcf-test-logging

**Comment by philloooo** [comment]
➤ Alex commented:

Production Logs: gs://dcf-logs

**Comment by philloooo** [comment]
➤ Alex commented:

Schema for Google Access logs: [http://storage.googleapis.com/pub/cloud_storage_usage_schema_v0.json](http://storage.googleapis.com/pub/cloud_storage_usage_schema_v0.json)

**Comment by philloooo** [comment]
➤ Alex commented:

Updated Data Transfer SOP doc with info about production bucket access logging.

**Comment by philloooo** [comment]
➤ Alex commented:

I created a sink from Cloud Audit Logging to Google's BigQuery.

Message from Google:

Export sink *dcfcloud_audit_logs* was successfully created._

__ 

A unique service account, *p643588826559447207@gcpsalogging.iam.gserviceaccount.com, has been created with permissions to write logs to the destination, bigquery.googleapis.com/projects/dcfprod-buckets/datasets/dcfcloud_audit_logs*._

**Comment by philloooo** [comment]
➤ Alex commented:

I have enabled both Cloud Audit Logging (which dumps data to a BigQuery table) and Data Access Logs (which dump data to a Cloud Storage Bucket). Data Access Logs are required in addition to Cloud Audit Logging to record access to OPEN data (e.g. allAuthenticatedUsers)

**Comment by philloooo** [comment]
➤ Alex commented:

Logs are under Google Project: dcfprodbuckets

Google Organization: nci-crdc.datacommons.io
