### ISSUE TITLE
support linking and unlinking user google account

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#28]
link google account via going through google oauth2 to verify user identity, store the linkage in the userdatamodel, add user's google account to user's proxy group

**Comment by Avantol13** [comment]
7 hr work in sprint 5

**Comment by Avantol13** [comment]
Grossly underestimated this one. Had some trouble debugging at the beginning (lots of redirection with oauth2 flow). Also had to set up dev env to work with Google to test in the stack. That coupled with unit tests and error handling made it take much longer than anticipated. There's more endpoints than just linking as well (which I'm still working on) like the DELETE endpoint to remove linkage. 

Hours - Day
1 - Thurs
5 - Fri
2 - Mon
2 - Tues
7 - Wed
7 - Th
5 - M
4 - Tues
6 - Wed
3 - Thurs
