### ISSUE TITLE
Include `nonce` claim in the ID token

### ISSUE THREAD

**Issue by VJalili** [uc-cdis/fence#600]
The `nonce` claim is optional; however, some clients (e.g., Galaxy) and authorization servers (e.g., Google) use it to mitigate replay attacks.

While this claim is optional, according to OIDC specifications, the authorization server (e.g., Fence) must include this claim in ID token if client (e.g,. Galaxy) has included `nonce` in authnz request: 

> If present in the Authentication Request, Authorization Servers MUST include a nonce Claim in the ID Token with the Claim Value being the nonce value sent in the Authentication Request.
([Ref](https://openid.net/specs/openid-connect-core-1_0.html#IDToken))

Galaxy includes `nonce` in its authentication request, but Fence does not return it as part of the ID token, hence making it invalid: 

- Authentication request generated by Galaxy:
    ```
    https://localhost/user/oauth2/authorize?
    nonce=30opsHCoh2EExNaqJ99kXSbXP2wlHrV36t509iaKzOfKmRLGbMEcFhP0EP7k4cPQ&
    state=9qL0CFv441knQYMycaTXcGzM1J4DKugd&
    redirect_uri=http://localhost:8080/authnz/fence/callback&
    response_type=code&
    client_id=UST2wwfQZZh9U6rybdJ6orAOo04uffCkW9QQWxUD&
    scope=openid+user&
    access_type=offline
    ```

- Decoded payload of an ID token sent by Fence:
    ```
    {
      "aud": [
        "openid",
        "user",
        "UST2wwfQZZh9U6rybdJ6orAOo04uffCkW9QQWxUD"
      ],
      "iss": "https://localhost/user",
      "iat": 1553700924,
      "jti": "019b2c62-d2ab-4a86-a8e3-32b33831fc0f",
      "context": {
        "user": {
          "phone_number": null,
          "display_name": null,
          "name": "xyz@gmail.com",
          "is_admin": false,
          "policies": [],
          "email": null,
          "projects": {}
        }
      },
      "auth_time": 1553700924,
      "azp": "UST2wwfQZZh9U6rybdJ6orAOo04uffCkW9QQWxUD",
      "exp": 1553702124,
      "pur": "id",
      "sub": "4"
    }
    ```

**Comment by Avantol13** [comment]
should be fixed as of https://github.com/uc-cdis/fence/releases/tag/4.1.1

**Comment by VJalili** [comment]
Thank you @Avantol13
